# Example Research Agent Configuration
llm:
  provider: claude
  model: claude-sonnet-4-20250514

tools_dir: src/agentwerkstatt/tools/
verbose: false

personas:
  - id: planner
    name: "Planner"
    description: "A persona that plans and delegates tasks."
    file: "examples/research_agent/personas/planner.md"
  - id: researcher
    name: "Researcher"
    description: "A persona that specializes in researching the web."
    file: "examples/research_agent/personas/researcher.md"
  - id: writer
    name: "Writer"
    description: "A persona that specializes in writing reports."
    file: "examples/research_agent/personas/writer.md"

default_persona: "planner"

# Optional: Langfuse configuration for observability
# langfuse:
#   enabled: false
#   project_name: "multi-agent-example"
