# AgentWerkstatt Configuration
# Configuration file for the minimalistic agent framework

# LLM Model Configuration
llm:
  provider: "claude"
  model: "claude-sonnet-4-20250514"

default_persona: "databot"
# Tools Configuration (uncomment if you want to use your own tools)
tools_dir: "../tools/"

# Logging Configuration
verbose: true

# Langfuse Configuration (Optional)
langfuse:
  enabled: true  # Set to false to disable Langfuse tracing
  project_name: "agentwerkstatt"  # Optional: Name for organizing traces

# Memory Configuration (Optional)
memory:
  enabled: true  # Set to true to enable mem0 integration
  model_name: "gpt-4o-mini"  # Model for memory processing
  server_url: "http://localhost:8000"  # mem0 server endpoint
