name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for setuptools-scm

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --dev
        uv pip install -e ".[observability,memory]"

    - name: Start services
      run: docker compose -f third_party/docker-compose.yaml up -d

    - name: Check service status
      run: |
        docker compose -f third_party/docker-compose.yaml ps
        sleep 10 # Give services time to start
        docker compose -f third_party/docker-compose.yaml logs

    - name: Run linting with ruff
      run: |
        uv run ruff check .

    - name: Run formatting check with ruff
      run: |
        uv run ruff format --check .

    - name: Run type checking with mypy
      run: |
        uv run mypy .

    - name: Run tests with pytest
      env:
        ANTHROPIC_API_KEY: "test"
        LANGFUSE_SECRET_KEY: "test"
        LANGFUSE_PUBLIC_KEY: "test"
        LANGFUSE_HOST: "http://localhost:3000"
      run: |
        uv run pytest --cov=src/agentwerkstatt --cov-report=xml --cov-report=term

    - name: Run end-to-end test
      run: |
        uv tool install build
        uv tool run --from build pyproject-build
        uv pip install dist/*.whl
        uv run pytest tests/test_agent_end_to_end.py -v

    - name: Stop services
      if: always()
      run: docker compose -f third_party/docker-compose.yaml down

    - name: Upload coverage reports to Codecov
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        disable_search: true

  build:
    needs: quality-checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for setuptools-scm

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install build dependencies
      run: |
        uv tool install build

    - name: Build package
      run: |
        uv tool run --from build pyproject-build

    - name: Check package
      run: |
        uv tool install twine
        uv tool run --from twine twine check dist/*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ github.sha }}
        path: dist/

  publish-test:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: test-pypi

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for setuptools-scm

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Check if version has local identifier
      id: version_check
      run: |
        uv sync --dev
        VERSION=$(uv run python -c "import setuptools_scm; print(setuptools_scm.get_version())")
        echo "Version: $VERSION"
        if [[ "$VERSION" == *"+"* ]]; then
          echo "Version contains local identifier (+), skipping test-pypi deployment"
          echo "skip_deployment=true" >> $GITHUB_OUTPUT
        else
          echo "Version is clean, proceeding with test-pypi deployment"
          echo "skip_deployment=false" >> $GITHUB_OUTPUT
        fi

    - name: Download build artifacts
      if: steps.version_check.outputs.skip_deployment == 'false'
      uses: actions/download-artifact@v4
      with:
        name: dist-${{ github.sha }}
        path: dist/

    - name: Publish to Test PyPI
      if: steps.version_check.outputs.skip_deployment == 'false'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        uv tool run --from twine twine upload --repository testpypi dist/*

  publish-prod:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    environment: pypi

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-${{ github.sha }}
        path: dist/

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        uv tool run --from twine twine upload dist/*
